// Test generated by RoostGPT for test Test28Sept using AI Type Open AI and AI Model gpt-4

const request = require('supertest');
const express = require('express');
const CustomerModel = require('../models/customer');
const router = express.Router();

jest.mock('../models/customer');

describe('GET /', () => {
  beforeEach(() => {
    CustomerModel.find.mockClear();
  });

  test('should return a list of customers on success', async () => {
    const mockCustomers = [{ id: 1, name: 'John Doe' }, { id: 2, name: 'Jane Doe' }];
    CustomerModel.find.mockResolvedValue(mockCustomers);

    const response = await request(router).get('/');

    expect(response.status).toBe(200);
    expect(response.body).toEqual(mockCustomers);
    expect(CustomerModel.find).toHaveBeenCalledTimes(1);
  });

  test('should return an error if the database query fails', async () => {
    const mockError = new Error('Database error');
    CustomerModel.find.mockRejectedValue(mockError);

    const response = await request(router).get('/');

    expect(response.status).toBe(500);
    expect(response.text).toEqual(mockError.message);
    expect(CustomerModel.find).toHaveBeenCalledTimes(1);
  });
});
